first draft
eclipse-uprotocol/uprotocol-platform-linux-zenoh pull request #1
Opened 2023-12-07 08:37 UTC by xz62px

2023-12-07 08:45 UTC, MelamudMichael commented on src/zenohSessionManager.cpp
> +
add mutex

2023-12-07 08:45 UTC, MelamudMichael commented on src/zenohSessionManager.cpp
> +
add mutex

2023-12-07 19:50 UTC, stevenhartley commented
@MelamudMichael don't forget the required Apache header files along with the required legal documents (CONTRIBUTING.adoc, NOTIC.adoc, LICENSE)

2023-12-12 23:55 UTC, linsonittoop requested changes
Comments from a  partial review.

2023-12-12 23:55 UTC, linsonittoop commented on src/zenohUTransport.cpp
> +        cbArgumentType *arg = new cbArgumentType(std::move(uri),
Avoid Duplicate definition of cbArgumentType with same name _arg_

2023-12-12 23:55 UTC, linsonittoop commented on src/zenohUTransport.cpp
> +        cbArgumentType *arg = new cbArgumentType(std::move(uri),
Is the _arg_ pointer stored and deallocated properly?

2023-12-13 17:22 UTC, MelamudMichael commented on src/messageParser.cpp
> +    // if (map.find(Tag::TOKEN) != map.end()) {
i will uncomment

2023-12-13 17:25 UTC, MelamudMichael commented on src/messageParser.cpp
> +    return UPayload(tlvPayload.value.data(),
need to align 1.5 branch

2023-12-13 17:27 UTC, MelamudMichael commented on src/zenohRpcClient.cpp
> +    ZenohSessionManagerConfig config;
initialize strings to null

2023-12-13 17:29 UTC, MelamudMichael commented on src/zenohUTransport.cpp
> +        if (true == message.size()) {
should be 0

2023-12-14 09:01 UTC, MelamudMichael commented on src/zenohUTransport.cpp
> +UCode ZenohUTransport::authenticate(const UEntity &uEntity)
it is not implemented yet

2023-12-14 10:22 UTC, MelamudMichael commented on src/messageBuilder.cpp
> +    // pos = addTag(message,
no

2023-12-14 16:31 UTC, linsonittoop requested changes

2024-01-08 22:37 UTC, stevenhartley commented
This was created to the wrong project

2024-01-08 22:37 UTC, closed without merging